version: '3'
services:
# 作成するコンテナを定義
    nginx:
        image: nginx:1.15
        # nginxコンテナの元になるイメージを指定
        ports:
            - 80:80
            # ホスト側の80番ポートとコンテナ側の80番ポートをつなげる
        volumes:
            - ./source:/usr/share/nginx/html/index.php
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    php-fpm:
        build: ./php-fpm
        # このコンテナの元になるDockerfileがおいてあるパスを指定します
        volumes:
            - ./source:/var/www/html
        # PHP-FPMコンテナでもホストPC側のプログラムソースディレクトリをマウントする
    mysql:
        image: mysql:latest
        # mysqlの認証方式が新しくなった→従来のPDOのコマンドでは対応してない
        command: --default-authentication-plugin=mysql_native_password
        environment:
        # MYSQLコンテナ作成時に初期作成されるデータベースの名前やユーザ。パスワードの設定
        # ユーザー名やデータベース名を変えたら、docker-compose build --no-cacheでキャッシュを消す
            MYSQL_DATABASE: quizy_db
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: maria
            MYSQL_PASSWORD: password
            TZ: Asia/Tokyo
        ports:
            - 3306:3306
        volumes:
            # - ./mysql/data:/var/lib/mysql dataを手元に持つため。docker-composeするたびにdataフォルダが作られるけど、毎回立ち上げるたびに消さなきゃいけないからいらなくない？
            - ./mysql/sql:/docker-entrypoint-initdb.d
            - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf


            # imageは最初に書くべき
            # build: ./mysql/mysqlフォルダの下のドッカーファイルをビルドする
            
